# Generated by Django 6.1.1 on 2026-09-08 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LookupOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('driver', 'Driver Type'), ('cri', 'CRI'), ('cct', 'CCT'), ('beam', 'Beam Angle'), ('body_colour', 'Body Colour / RAL Finish'), ('option', 'Option'), ('emergency', 'Emergency Backup'), ('install_method', 'Install Method'), ('lamp_type', 'Lamp Type'), ('light_dist', 'Light Distribution'), ('ip_rating', 'IP Rating'), ('driver_mount', 'Driver Mount')], max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['attribute', 'sort_order', 'label'],
                'unique_together': {('attribute', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20)),
                ('family_name', models.CharField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='configurator.category')),
            ],
            options={
                'ordering': ['category__name', 'prefix'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, default='', max_length=300)),
                ('batch_id', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_skus', to='configurator.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
